version: "3"
services:
  sonos:
    image: chrisns/docker-node-sonos-http-api:latest
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=sonos.p.cns.me
        - com.df.servicePath=/
        - com.df.port=5005
networks:
  outside:
    external:
      name: "host"